/*********************************************************
 **
 ** File  S2A_UA_1_LAY_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version 18.0 (build i12)
 ** 
 ** Date of generation: 2017-10-27T20:33:53
 ** Command line: C:/Program Files/ANSYS Inc/v180/SCADE/SCADE/bin/uaadaptor.exe -sdy C:\Users\victo\Desktop\STAMPS\UserApplication\S2A\S2A.sdy -n C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Display\config\a661_description\a661.xml -outdir C:/Users/victo/Desktop/STAMPS/UserApplication/S2A/Simulation -k C:/Users/victo/Desktop/STAMPS/UserApplication/S2A/Simulation/kcg_trace.xml -o S2A_UA_1 -i S2A_interface.h -encoding ASCII C:\Users\victo\Desktop\STAMPS\DefinitionFile\S2A\S2A.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "S2A_UA_1.h"
#include "S2A_UA_1_constants.h"
#include "S2A_UA_1_private.h"

/* Perform UA Request for layer 1 */
A661_INTERNAL uaa_size a661_com_A661_CMD_UA_REQUEST_layer_1(buffer_el msg[], 
  outC_S2A* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->ReqLayerVisible ||
  scade_ctx->ReqLayerActive){
    
    if (scade_ctx->ReqLayerVisible){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_VISIBLE, 0);
    }
    if (scade_ctx->ReqLayerActive){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_ACTIVE, 0);
    }
  }
  return offset ;
}

/* Pack messages for layer 1 */
 uaa_size a661_com_layer_1(buffer_el msg[], 
  outC_S2A* scade_ctx,  extern_out_ctx_t* extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->EmitToDisplay ||
  scade_ctx->ReqLayerActive ||
  scade_ctx->ReqLayerVisible){
    LAYER("a661_layer#1");
    offset = 8;
    a661_msg_cmd_header(msg, 1, S2A_UA_1_DEFAULT_CONTEXT_NUMBER);
    if (scade_ctx->EmitToDisplay){
      WIDGET("NumericReadout#7");
      offset = offset + a661_com_csp_widget_NumericReadout(msg + offset, 7,
        scade_ctx->EmitToDisplay, scade_ctx->Debug);
    }
    if (scade_ctx->ReqLayerActive ||
    scade_ctx->ReqLayerVisible){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_layer_1(msg + offset,
        scade_ctx, extern_ctx);
    }
    WRITE_ULONG(msg + offset, A661_END_BLOCK);
    offset = offset + 4;
    WRITE_ULONG(msg + 4, offset);
  }
  return offset ;
}

/*********************************************************
 ** End of file
 ** End of generation: 2017-10-27T20:33:53
 *********************************************************/

