/*********************************************************
 **
 ** File  batimento_UA_1_LAY_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version R17 (build i15)
 ** 
 ** Date of generation: 2017-10-26T20:32:25
 ** Command line: C:/Program Files (x86)/Esterel Technologies/SCADE R17/SCADE/bin/uaadaptor.exe -sdy C:\Users\victo\SCADE\batimento\batimento.sdy -n C:\Program Files (x86)\Esterel Technologies\SCADE R17\SCADE Display\config\a661_description\a661.xml -outdir C:/Users/victo/SCADE/batimento/Simulation -k C:/Users/victo/SCADE/batimento/Simulation/kcg_trace.xml -o batimento_UA_1 -i batimento_interface.h -encoding ASCII C:\Users\victo\display_saude\UADF.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "batimento_UA_1.h"
#include "batimento_UA_1_constants.h"
#include "batimento_UA_1_private.h"

/* Perform UA Request for layer 1 */
A661_INTERNAL uaa_size a661_com_A661_CMD_UA_REQUEST_layer_1(buffer_el msg[], 
  outC_batimento* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->Emit){
    
    if (scade_ctx->Emit){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_VISIBLE, 0);
    }
    if (scade_ctx->Emit){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_ACTIVE, 0);
    }
  }
  return offset ;
}

/* Pack messages for layer 1 */
 uaa_size a661_com_layer_1(buffer_el msg[], 
  outC_batimento* scade_ctx,  extern_out_ctx_t* extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->Emit){
    LAYER("a661_layer#1");
    offset = 8;
    a661_msg_cmd_header(msg, 1, batimento_UA_1_DEFAULT_CONTEXT_NUMBER);
    if (scade_ctx->Emit){
      WIDGET("GpRectangle#33");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 33,
        scade_ctx->Emit, scade_ctx->p1);
    }
    if (scade_ctx->Emit){
      WIDGET("GpRectangle#34");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 34,
        scade_ctx->Emit, scade_ctx->p2);
    }
    if (scade_ctx->Emit){
      WIDGET("GpRectangle#35");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 35,
        scade_ctx->Emit, scade_ctx->p3);
    }
    if (scade_ctx->Emit){
      WIDGET("GpRectangle#36");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 36,
        scade_ctx->Emit, scade_ctx->p4);
    }
    if (scade_ctx->Emit){
      WIDGET("GpRectangle#37");
      offset = offset + a661_com_csp_widget_GpRectangle(msg + offset, 37,
        scade_ctx->Emit, scade_ctx->p5);
    }
    if (scade_ctx->Emit){
      WIDGET("NumericReadout#41");
      offset = offset + a661_com_csp_widget_NumericReadout(msg + offset, 41,
        scade_ctx->Emit, scade_ctx->atual);
    }
    if (scade_ctx->Emit){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_layer_1(msg + offset,
        scade_ctx, extern_ctx);
    }
    WRITE_ULONG(msg + offset, A661_END_BLOCK);
    offset = offset + 4;
    WRITE_ULONG(msg + 4, offset);
  }
  return offset ;
}

/*********************************************************
 ** End of file
 ** End of generation: 2017-10-26T20:32:25
 *********************************************************/

