/*********************************************************
 **
 ** File  batimento_UA_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version R17 (build i15)
 ** 
 ** Date of generation: 2017-10-26T20:32:25
 ** Command line: C:/Program Files (x86)/Esterel Technologies/SCADE R17/SCADE/bin/uaadaptor.exe -sdy C:\Users\victo\SCADE\batimento\batimento.sdy -n C:\Program Files (x86)\Esterel Technologies\SCADE R17\SCADE Display\config\a661_description\a661.xml -outdir C:/Users/victo/SCADE/batimento/Simulation -k C:/Users/victo/SCADE/batimento/Simulation/kcg_trace.xml -o batimento_UA_1 -i batimento_interface.h -encoding ASCII C:\Users\victo\display_saude\UADF.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "batimento_UA_1.h"
#include "batimento_UA_1_constants.h"
#include "batimento_UA_1_private.h"

/********************************************************************************************
 * Send messages to the A661 server                                                         *
 ********************************************************************************************/
 uaa_size batimento_UA_1_send(buffer_el msg[], 
  outC_batimento* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  
  offset = offset + a661_com_layer_1(msg + offset, scade_ctx, extern_ctx);
  return offset ;
}

/********************************************************************************************
 * Receive notifications from the A661 server                                               *
 ********************************************************************************************/
uaa_size batimento_UA_1_receive(buffer_el buffer[],  uaa_size buffer_size, 
  void* scade_ctx,  extern_in_ctx_t * extern_ctx){
  /*  No input in SCADE Suite model, function intentionally left empty */
  return 0 ;
}

/********************************************************************************************
 * Clear notifications                                                                      *
 ********************************************************************************************/
void batimento_UA_1_receive_clear(void* scade_ctx, 
  extern_in_ctx_t * extern_ctx){
  
}

/*********************************************************
 ** End of file
 ** End of generation: 2017-10-26T20:32:25
 *********************************************************/

